### ISSUE TITLE
Drop down menu won't submit

### ISSUE THREAD

**Issue by Blenderman18** [katzwebservices/Contact-Form-7-Newsletter#44]
I created a drop down menu using the Generate Tag / Constant Contact Lists button. When I click submit on the page that has this form it just hangs with the arrow graphic spinning indefinitely. If I delete the drop down code or if I use checkboxes instead it works perfect, it submits, it is added to constant contact, etc. I don't understand why the dropdown will not work? Any ideas? Do you need any further info from me? I need to create a drop down list for each state, we have a different list depending on the state you are in. So using checkboxes doesn't work for me, it takes up too much room on the page.

Edit* I just noticed that I will actually receive the email submission. The page just hangs there however, with spinning arrow and doesn't give the message to the user that the message was sent (in my case I forward to a thank you page), nor does it submit the contact info/email address to constant contact.

**Comment by Blenderman18** [comment]
Here is a link to a test form on my site. http://trucksafety.org/test-2/

**Comment by Blenderman18** [comment]
I can't be the only one with this issue. I have turned off all plugins except contact form 7 and contact form 7 newsletter and turned on the default theme, twenty fifteen and it is still doing this. When I turn off the newsletter plugin leaving contact form 7 only the form works. What else could it be ... It has to be with the plugin. Again the email is delivered, but the spinning icon just keeps spinning and the user gets no confirmation that the email was sent from the website. This only seems to be happening when you create a drop down list. The opt in and check boxes both work fine. Just when I have a drop down menu created with the Generate Tag / Constant Contact Lists button does this happen. What can I do to fix this?

**Comment by zackkatz** [comment]
This should be fixed with the latest release (2.1). Please try it and let me know.

**Comment by Blenderman18** [comment]
Wow. Thanks so much for the update. I’ll try it tonight.

**Comment by Blenderman18** [comment]
No it doesn’t fix my problem. Here is links to a test so you can see what it is doing. http://trucksafety.org/test-2/

Thanks.

**Comment by Blenderman18** [comment]
The other options work fine, such as the checkbox's. I just can't figure this out. I tried in on numerous different sites and on a fresh wordpress install to make sure there weren't any conflicts with themes or plugins and it does this same thing on the fresh site as well. When there is a drop down on the form that is connected to cc, it hangs when you submit. The emails go through but you don't get a confirmation on the page (the green box) nor do the emails get submitted to cc. Any ideas? I can't be the only one who is experiencing this.
